[workspace]
channels = ["https://prefix.dev/conda-forge"]
platforms = ["win-64", "linux-64"]
preview = ["pixi-build"]

[package]
name = "melops-export"
version = "0.1.0"

[package.build.backend]
channels = ["https://prefix.dev/conda-forge"]
name = "pixi-build-python"
version = ">=0.4.2,<0.5"

[package.build.config]
noarch = true

[package.build-dependencies]
cxx-compiler = ">=1.11.0,<1.12"
cmake = ">=4.2.1,<4.3"

[package.host-dependencies]
python = ">=3.13.10,<3.14"
uv = ">=0.9.21,<0.10"
uv-build = ">=0.9.21,<0.10"
